#!/bin/bash

FILE="$HOME/.cache/eww_launch.xyz"
EWW="/usr/bin/eww"

# Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

# Open widgets
run_eww() {
	${EWW} open bar
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close-all && killall eww && run_eww
fi