add_newline = false

[character]
success_symbol = "[╰─λ](bold blue)"
error_symbol = ""

[directory]
format = "[╭─$path]($style) [$read_only]($read_only_style)"
style = "bold blue"
read_only = " "
read_only_style = "blue"

[cmd_duration]
min_time = 1_000

[fill]
symbol = " "

[git_branch]
style = "bold cyan"

[git_metrics]
disabled = false

[nodejs]
style = "bold green"

[package]
disabled = true

[python]
symbol = " "

[status]
disabled = false
map_symbol = true
symbol = "×"
not_found_symbol = "󰍉"
not_executable_symbol = ""
sigint_symbol = "󰂭"
signal_symbol = "󱑽"
success_symbol = ""
format = "[╰─](bold blue)[$symbol](bold red) "
