# This file contains my personal list of
# both GUI and CLI applications that I use
# that aren't necessarily dependencies of my dotfiles

- yay:
    # CLI Applications
    - docker
    - docker-compose
    - docker-credential-secretservice-bin
    - downgrade
    - needrestart
    - pnpm
    - plocate
    - proton-ge-custom-bin
    # GUI Applications
    - nwg-look-bin
    - qt6ct
    - xwaylandvideobridge-bin
    - uv

- flatpak:
    - com.stremio.Stremio

- shell:
    - [updatedb, Updating locate database]
