# This file contains my personal list of
# both GUI and CLI applications that I use
# that aren't necessarily dependencies of my dotfiles

- yay:
    # CLI Applications
    - downgrade # no (pacman only)
    - plocate # no (os dependency)
    - proton-ge-custom-bin # no (likely needs to be system module)
    - uv # no (will figure out python dev later)
    # GUI Applications

- shell:
    - [updatedb, Updating locate database]
