# This file contains my personal list of
# both GUI and CLI applications that I use
# that aren't necessarily dependencies of my dotfiles

- yay:
    # CLI Applications
    - bottom
    - boxxy
    - docker
    - docker-compose
    - docker-credential-secretservice-bin
    - downgrade
    - duf
    - gamemode
    - hwinfo
    - lf
    - mangohud
    - needrestart
    - ncdu
    - pnpm
    - plocate
    - proton-ge-custom-bin
    - rye
    - scc
    - thefuck
    - tldr
    - unrar
    - unzip
    - zip
    # GUI Applications
    - discord
    - discord-ptb
    - zen-browser-avx2-bin
    - insomnia-bin
    - mattermost-desktop-bin
    - nwg-look-bin
    - obs-studio
    - obsidian
    - qt6ct
    - spotify-launcher
    - steam
    - trashy-git
    - vesktop
    - xwaylandvideobridge-bin
    - zoom

- flatpak:
    - com.stremio.Stremio
    - com.heroicgameslauncher.hgl

- shell:
    - [updatedb, Updating locate database]
