#!/usr/bin/env bash

set -e

CONFIG_SUFFIX=".conf.yaml"
DEFAULT_CONFIG_PREFIX="install"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="dotbot-yay"

cd "${BASE_DIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}" "${PLUGIN_DIR}"

for conf in ${DEFAULT_CONFIG_PREFIX} ${@}; do
    "${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "${conf}${CONFIG_SUFFIX}" \
        --plugin-dir "$PLUGIN_DIR"
done

# Cleanup
rm -rf dotbot-yay/__pycache__