#!/usr/bin/env bash
set -e

[[ -n $HYPRLAND_DEBUG_CONF ]] && exit 0
USAGE="\
Import environment variables 

Usgae: $0 <command>

Commands:
   tmux         import to tmux server
   system       import to systemd and dbus user session
   help         print this help
"

_envs=(
	# Display
	WAYLAND_DISPLAY
	DISPLAY
	# XDG
	USERNAME
	XDG_BACKEND
	XDG_SESSION_ID
	XDG_SESSION_CLASS
	XDG_SEAT
	XDG_VTNR
	# hyprland
	HYPRLAND_CMD
	HYPRLAND_INSTANCE_SIGNATURE
	# toolkit
	_JAVA_AWT_WM_NONREPARENTING
	# ssh
	SSH_AUTH_SOCK
)

mapfile -t -O "${#_envs[@]}" _envs < <(rg '^env? =' ../conf.d/environment.conf | awk '{print $3}' | tr -d ',')

case "$1" in
system)
	dbus-update-activation-environment --systemd "${_envs[@]}"
	;;
tmux)
	for v in "${_envs[@]}"; do
		if [[ -n ${!v} ]]; then
			tmux setenv -g "$v" "${!v}"
		fi
	done
	;;
help)
	echo -n "$USAGE"
	exit 0
	;;
*)
	echo "operation reuqired"
	echo "use \"$0 help\" to see usage help"
	exit 1
	;;
esac
