#!/bin/sh

if ! pgrep -x foot >/dev/null; then
  hyprctl dispatch exec 'foot --server'
  until pgrep -x foot; do sleep 0.05; done
  hyprctl dispatch exec 'notify-send "Foot Terminal" "Server is not running, starting it now..."'
  hyprctl dispatch exec "footclient $*"
else
  hyprctl dispatch exec "footclient $*"
fi
