#!/bin/bash

# This script is used to move the current window to the TV workspace and back.

# Arguments:

ULTRAWIDE_MONITOR=$1
TV_WORKSPACE=$2
TV_MONITOR_NAME=$3
TV_MONITOR_SETTINGS=$4

# Constants:

TEMP_DIR=/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE
TEMP_FILE=$TEMP_DIR/tv_was_on_workspace

# Script:

move_to_tv() {
  current_info=$(hyprctl activewindow -j | jq "[.address, .workspace.id]" --raw-output)
  tv_window_address=$(echo $current_info | jq .[0] --raw-output)
  tv_was_on=$(echo $current_info | jq .[1] --raw-output)
  hyprctl --batch "keyword monitor $TV_MONITOR_NAME,$TV_MONITOR_SETTINGS; keyword workspace $TV_WORKSPACE, monitor:$TV_MONITOR_NAME"
  # This doesn't work when in the batch
  hyprctl dispatch movetoworkspace $TV_WORKSPACE,address:$tv_window_address
  echo "$tv_was_on,$tv_window_address" > $TEMP_FILE

}

move_away_tv() {
  tv_was_on=$(cat $TEMP_FILE | cut -d ',' -f 1)
  tv_window_address=$(cat $TEMP_FILE | cut -d ',' -f 2)
  rm $TEMP_FILE
  hyprctl --batch "dispatch movetoworkspace $tv_was_on,address:$tv_window_address; keyword monitor $TV_MONITOR_NAME, disable;"
}

if [ ! -f $TEMP_FILE ]; then
  move_to_tv
else
  move_away_tv
fi
