#!/bin/sh


LOCK_FILE="$HOME/.cache/eww-calendar.lock"
EWW_BIN="/usr/bin/eww"

if [[ ! `pidof eww` ]]; then
    ${EWW_BIN} daemon
    sleep 1
fi

open() {
    ${EWW_BIN} open calendar
    ${EWW_BIN} open calendar-closer
    touch "$LOCK_FILE"
}

close() {
    ${EWW_BIN} close calendar
    ${EWW_BIN} close calendar-closer
    rm "$LOCK_FILE"
}

if [[ ! -f $LOCK_FILE ]]; then
  open
else
  close
fi