#
# ~/.bashrc
#

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_RUNTIME_DIR=/run/user/1000

export ASDF_CONFIG_FILE=$XDG_CONFIG_HOME/asdf/asdfrc
export ASDF_DATA_DIR=$XDG_DATA_HOME/asdf
export BUN_INSTALL=$XDG_DATA_HOME/bun
export CARGO_HOME=$XDG_DATA_HOME/cargo
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export GRADLE_USER=$XDG_DATA_HOME/gradle
export __JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export PYTHON_HISTORY=$XDG_DATA_HOME/python/history
export PYENV_ROOT=$XDG_DATA_HOME/pyenv
export RYE_HOME=$XDG_DATA_HOME/rye
export GOPATH=$XDG_DATA_HOME/go
export GOMODCACHE=$XDG_CACHE_HOME/go/mod
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export HISTFILE=$XDG_DATA_HOME/bash/history

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[[ "$(whoami)" = "root" ]] && return

[[ -z "$FUNCNEST" ]] && export FUNCNEST=100 # limits recursive functions, see 'man bash'

## Use the up and down arrow keys for finding a command in history
## (you can write some initial letters of the command first).
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket

PATH=~/.local/bin:$PATH
PATH=~/.local/share/cargo/bin:$PATH
PATH=~/.local/share/rye/bin:$PATH
PATH=~/.local/share/go/bin:$PATH

source "$HOME/.rye/env
