[mgr]
ratio = [1, 1, 3]
show_hidden = true
sort_by = "alphabetical"
sort_sensitive = false
sort_dir_first = true
show_symlink = true
scrolloff = 200

[plugin]
prepend_previewers = [{ name = "*/", run = "eza-preview" }]
